// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build/build-index.js
//
// DO NOT UPDATE THIS FILE DIRECTLY
import RCalendar from './components/RCalendar';
import RSearch from './components/RSearch';

// Export components individually
export { RCalendar, RSearch };

// What should happen if the user installs the library as a plugin
function install(Vue) {
    Vue.component('RCalendar', RCalendar);
    Vue.component('RSearch', RSearch);
}

// Export the library as a plugin
export default { install: install };
